# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GILapp', '0002_blog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='blog',
        ),
    ]
