# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 11:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GILapp', '0003_auto_20170725_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogy',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
