# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GILapp', '0006_remove_blogy_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogy',
            name='author',
        ),
    ]
