# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GILapp', '0008_blogy_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogy',
            name='slug',
            field=models.SlugField(max_length=250, null=True),
        ),
    ]
