# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GILapp', '0011_remove_blogetc_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogetc',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GILapp.blogy'),
        ),
    ]
