# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GILapp', '0012_auto_20170801_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogetc',
            name='user',
        ),
        migrations.DeleteModel(
            name='blogetc',
        ),
    ]
