# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GILapp', '0013_auto_20170801_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogetc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(null=True, upload_to='pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GILapp.blogy')),
            ],
        ),
    ]
