# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GILapp', '0014_blogetc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogetc',
            old_name='user',
            new_name='title',
        ),
    ]
