# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GILapp', '0015_auto_20170801_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogetc',
            name='title',
        ),
        migrations.AddField(
            model_name='blogy',
            name='pic',
            field=models.FileField(null=True, upload_to='pic'),
        ),
        migrations.DeleteModel(
            name='blogetc',
        ),
    ]
