# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GILapp', '0016_auto_20170801_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_cmnt', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('cmt_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GILapp.blogy')),
            ],
        ),
    ]
